const userData = [
  {
    first_name: "dana",
    last_name: "smith",
    username: "dSmith91",
    password: "testtest1",
    email: "dsmith@test.com",
    role: "member",
    phone: "9177777777",
  },
  {
    first_name: "chris",
    last_name: "falcon",
    username: "bird_guy",
    password: "testtest2",
    email: "birdguy@test.com",
    role: "member",
    phone: "9174444444",
  },
  {
    first_name: "sheri",
    last_name: "george",
    username: "sg1995",
    password: "testtest3",
    email: "sg@test.com",
    role: "member",
    phone: "2125555555",
  },
  {
    first_name: "clarence",
    last_name: "samuel",
    username: "clary55",
    password: "testtest4",
    email: "c.sam@test.com",
    role: "admin",
    phone: "2129999999",
  },
  {
    first_name: "audrey",
    last_name: "alister",
    username: "aatesting",
    password: "testtest5",
    email: "aa@test.com",
    role: "admin",
    phone: "2128888888",
  },
  {
    first_name: "franklin",
    last_name: "parker",
    username: "frparker",
    password: "testtest6",
    email: "franklin@test.com",
    role: "member",
    phone: "2121111111",
  },
  {
    first_name: "Lady",
    last_name: "Gaga",
    username: "ladygaga",
    password: "ghfgbnfgn",
    email: "ladygaga@user.com",
    role: "member",
    phone: "5918725656",
  },
  {
    first_name: "Britney",
    last_name: "Spears",
    username: "itsbritneyb",
    password: "bbbb",
    email: "britney@gmail.com",
    role: "member",
    phone: "3168795432",
  },
  {
    first_name: "Jane",
    last_name: "Yeh",
    username: "janeyeh",
    password: "jane",
    email: "janeyeh@matcha.com",
    role: "admin",
    phone: "5641208752",
  },
  {
    first_name: "Kate",
    last_name: "Grant",
    username: "kategrant",
    password: "kg",
    email: "kategrant@matcha.com",
    role: "admin",
    phone: "4425896324",
  },
  {
    first_name: "Sheyla",
    last_name: "De los Santos",
    username: "sheyladelossantos",
    password: "sheyla",
    email: "sheyladelossantos@matcha.com",
    role: "admin",
    phone: "52168752398",
  },
];

// {first_name: , last_name: , username: , password: , email: , role: , phone: }

const productData = [
  {
    name: "Delicious green",
    price: 30.95,
    quantity: 10,
    description: "A delicious blend of green teas",
    category: "tea",
  },
  {
    name: "Notorious",
    price: 40.95,
    quantity: 6,
    description: "A unique mix of flavors to energize your palate.",
    category: "tea",
  },
  {
    name: "The Whisk",
    price: 38.99,
    quantity: 20,
    description: "A whisk away from your foamy dreams",
    category: "accessories",
  },
  {
    name: "Spoonful",
    price: 9.95,
    quantity: 27,
    description: "The only spoon you need",
    category: "accessories",
  },
  {
    name: "White trouble",
    price: 24.95,
    quantity: 13,
    description: "Mischevous and aromatic",
    category: "tea",
  },
];

module.exports = { userData, productData };
